---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ayane-shortlink
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: ayane-shortlink
  replicas: 1
  template:
    metadata:
      labels:
        app: ayane-shortlink
    spec:
      imagePullSecrets:
        - name: internal-harbor
      containers:
        - name: app
          image: registry.uniproject.jp/ayane/shortlink:0.0.10
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: default-port
          resources:
            limits:
              memory: "2Gi"
              cpu: "2000m"
            requests:
              memory: "1Gi"
              cpu: "100m"
          env:
            - name: ORIGINAL_LINK
              valueFrom:
                secretKeyRef:
                  name: go-secret
                  key: ORIGINAL_LINK
            - name: API
              valueFrom:
                secretKeyRef:
                  name: go-secret
                  key: API
            - name: API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: go-secret
                  key: API_TOKEN
            - name: SHORT_CODE
              valueFrom:
                secretKeyRef:
                  name: go-secret
                  key: SHORT_CODE
            - name: SHORT_CODE_LENGTH
              valueFrom:
                secretKeyRef:
                  name: go-secret
                  key: SHORT_CODE_LENGTH
            - name: POSTGRES_HOST
              value: "ayane-shortlink-db"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: go-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: go-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: go-secret
                  key: POSTGRES_PASSWORD
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ayane-shortlink-db
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: ayane-shortlink-db
  replicas: 1
  template:
    metadata:
      labels:
        app: ayane-shortlink-db
    spec:
      imagePullSecrets:
        - name: internal-harbor
      containers:
        - name: postgres
          image: postgres:17
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: go-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: go-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: go-secret
                  key: POSTGRES_PASSWORD
            - name: TZ
              value: "Asia/Tokyo"
            - name: PGTZ
              value: "Asia/Tokyo"
            # PostgreSQL設定を環境変数で上書き
            - name: POSTGRES_INITDB_ARGS
              value: "--encoding=UTF8 --locale=ja_JP.UTF-8"
          volumeMounts:
            - name: postgres-persistent-storage
              mountPath: "/var/lib/postgresql/data"
      volumes:
        - name: postgres-persistent-storage
          persistentVolumeClaim:
            claimName: ayane-shortlink
