---
apiVersion: v1
kind: Service
metadata:
  name: ayane-shortlink
spec:
  selector:
    app: ayane-shortlink
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: ayane-shortlink-db
spec:
  selector:
    app: ayane-shortlink-db
  ports:
    - port: 5432
      targetPort: 5432
